# AutoCoder/.github/workflows/first_workflow.yml

name: First Workflow

on: push

jobs:
  say-hello:
    name: Name of first step
    runs-on: ubuntu-latest
    steps:
      #step 1
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      #step 2
      - name: Greeting Message
        run: echo "Hello, world!"

#  second-job:
#    strategy:
#      matrix:
#        runtimes: [10, 12, 14]
#        os_version: [ubuntu-latest, windows-latest]
#    runs-on: ${{ matrix.os_version}}
#    steps:
#      - uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.runtimes }}